name: Mini Pipeline

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Running tests"

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - run: echo "Building application"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying application"